{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/BarcodeApp/Actions/Barcode_app/Service/UploadOffline.action",
    "OnFailure": "/BarcodeApp/Actions/Barcode_app/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}